[package]
name = "platform-sdl2"
version = "0.1.0"
edition = "2021"

[dependencies]
sdl2 = { version = "*", features = ["image"] }
util = { path = "../../util" }
core = { path = "../../arc/core" }
graphic = { path = "../../arc/graphic" }
opengl = { path = "../../opengl" }
