[package]
name = "app"
version = "0.1.0"
edition = "2021"
build="build.rs"

[dependencies]
util = { path = "../util" }
core = { path = "../arc/core" }
graphic = { path = "../arc/graphic" }
vector = { path = "../arc/vector" }
platform-sdl2 = { path = "../platform/platform-sdl2" }
