[package]
name = "opengl"
version = "0.1.0"
edition = "2021"

[dependencies]
gl="*"
bitflags="*"
util = { path = "../util" }
core = { path = "../arc/core" }
graphic = { path = "../arc/graphic" }
image = { path = "../arc/image" }
vector = { path = "../arc/vector" }
